from fastapi.responses import HTMLResponse

def make_panel(name, total_str, used_str, rem_str, cnt, pct):
    bar = "#EF4444" if pct > 90 else "#F59E0B" if pct > 70 else "#10B981"
    html = "<!DOCTYPE html>"
    html += '<html lang="fa" dir="rtl">'
    html += "<head><meta charset='UTF-8'>"
    html += "<title>پنل نماینده</title>"
    html += "<style>"
    html += "*{margin:0;padding:0;box-sizing:border-box}"
    html += "body{font-family:Tahoma,sans-serif;background:#060f1d;color:#E8F4FF;padding:16px}"
    html += ".w{max-width:450px;margin:auto}"
    html += ".h{display:flex;justify-content:space-between;align-items:center;margin-bottom:16px}"
    html += ".c{background:rgba(10,22,40,0.9);border:1px solid rgba(139,92,246,0.2);border-radius:14px;padding:18px;margin-bottom:12px}"
    html += ".r{display:flex;gap:10px;flex-wrap:wrap}"
    html += ".b{flex:1;min-width:100px;padding:12px;background:rgba(139,92,246,0.05);border:1px solid rgba(139,92,246,0.15);border-radius:11px;text-align:center}"
    html += ".l{font-size:9px;color:#3D6B8E}"
    html += ".v{font-size:18px;font-weight:800}"
    html += ".br{height:5px;background:rgba(139,92,246,0.1);border-radius:3px;margin:10px 0}"
    html += ".bf{height:100%;border-radius:3px}"
    html += ".btn{font-size:11px;padding:7px 14px;border-radius:8px;border:1px solid rgba(139,92,246,0.2);background:transparent;color:#7BAED4;cursor:pointer;font-family:inherit}"
    html += ".ft{text-align:center;padding-top:12px;font-size:9px;color:#3D6B8E}"
    html += "</style></head><body><div class='w'>"
    html += "<div class='h'><div><b style='font-size:15px'>" + name + "</b><br><span style='font-size:10px;color:#3D6B8E'>نماینده</span></div>"
    html += "<form action='/api/logout' method='post' style='display:inline'><button class='btn' type='submit'>خروج</button></form></div>"
    html += "<div class='c'>"
    html += "<div style='display:flex;justify-content:space-between;font-size:12px;font-weight:700'>"
    html += "<span>مصرف: " + used_str + "</span><span>از " + total_str + "</span></div>"
    html += "<div class='br'><div class='bf' style='width:" + str(pct) + "%;background:" + bar + "'></div></div>"
    html += "<div style='display:flex;justify-content:space-between;font-size:9px;color:#3D6B8E'>"
    html += "<span>باقی: " + rem_str + "</span><span>" + str(pct) + "%</span></div></div>"
    html += "<div class='r'>"
    html += "<div class='b'><div class='l'>حجم کل</div><div class='v'>" + total_str + "</div></div>"
    html += "<div class='b'><div class='l'>باقیمانده</div><div class='v' style='color:" + bar + "'>" + rem_str + "</div></div>"
    html += "<div class='b'><div class='l'>کانفیگها</div><div class='v'>" + str(cnt) + "</div></div></div>"
    html += "<div class='c'><div style='font-size:12px;color:#7BAED4;line-height:2'><b>محدودیتها:</b><br>"
    html += "- حجم مجاز: " + total_str + "<br>"
    html += "- باقیمانده: " + rem_str + "<br>"
    html += "- کانفیگ نامحدود: ممنوع</div></div>"
    html += "<div class='ft'>VaslZone Gateway</div></div></body></html>"
    return HTMLResponse(content=html)
